// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnPaJGNigRNTXZURzgS_PW4KkqbXKqaBg',
    appId: '1:668408981680:web:2e5a0ef9f04856ee7cf375',
    messagingSenderId: '668408981680',
    projectId: 'borcmatik-v2',
    authDomain: 'borcmatik-v2.firebaseapp.com',
    storageBucket: 'borcmatik-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWCwxODqXw0aQYa1LW-A9VwAdLlvMTPXo',
    appId: '1:668408981680:android:3344a59a11fccda27cf375',
    messagingSenderId: '668408981680',
    projectId: 'borcmatik-v2',
    storageBucket: 'borcmatik-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdxygyOER1Znkxd-pXCjourcmH_zQgR6Y',
    appId: '1:668408981680:ios:c993a131245498fe7cf375',
    messagingSenderId: '668408981680',
    projectId: 'borcmatik-v2',
    storageBucket: 'borcmatik-v2.firebasestorage.app',
    iosBundleId: 'com.example.borcmatik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdxygyOER1Znkxd-pXCjourcmH_zQgR6Y',
    appId: '1:668408981680:ios:c993a131245498fe7cf375',
    messagingSenderId: '668408981680',
    projectId: 'borcmatik-v2',
    storageBucket: 'borcmatik-v2.firebasestorage.app',
    iosBundleId: 'com.example.borcmatik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnPaJGNigRNTXZURzgS_PW4KkqbXKqaBg',
    appId: '1:668408981680:web:2e7d3423142d7c927cf375',
    messagingSenderId: '668408981680',
    projectId: 'borcmatik-v2',
    authDomain: 'borcmatik-v2.firebaseapp.com',
    storageBucket: 'borcmatik-v2.firebasestorage.app',
  );

}